<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <RootNamespace>FACM</RootNamespace>
    <AssemblyName>FACM</AssemblyName>
    <Platforms>AnyCPU</Platforms>
    <Prefer32Bit>false</Prefer32Bit>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Deterministic>true</Deterministic>
    <DebugType>portable</DebugType>
    <DebugSymbols>true</DebugSymbols>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="System" />
    <Reference Include="System.Core" />
    <Reference Include="System.Drawing" />
    <Reference Include="System.Windows.Forms" />
    <Reference Include="System.Security" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\Fix-LCU-Window.exe.b64.part00"><LogicalName>FACM.Resources.FixLcu.Part00</LogicalName></EmbeddedResource>
    <EmbeddedResource Include="Resources\Fix-LCU-Window.exe.b64.part01"><LogicalName>FACM.Resources.FixLcu.Part01</LogicalName></EmbeddedResource>
    <EmbeddedResource Include="Resources\Fix-LCU-Window.exe.b64.part02"><LogicalName>FACM.Resources.FixLcu.Part02</LogicalName></EmbeddedResource>
    <EmbeddedResource Include="Resources\Fix-LCU-Window.exe.b64.part03"><LogicalName>FACM.Resources.FixLcu.Part03</LogicalName></EmbeddedResource>
    <EmbeddedResource Include="Resources\Fix-LCU-Window.exe.b64.part04"><LogicalName>FACM.Resources.FixLcu.Part04</LogicalName></EmbeddedResource>
    <EmbeddedResource Include="Resources\Fix-LCU-Window.exe.b64.part05"><LogicalName>FACM.Resources.FixLcu.Part05</LogicalName></EmbeddedResource>
    <EmbeddedResource Include="Resources\Fix-LCU-Window.exe.b64.part06"><LogicalName>FACM.Resources.FixLcu.Part06</LogicalName></EmbeddedResource>
    <EmbeddedResource Include="Resources\Fix-LCU-Window.exe.b64.part07"><LogicalName>FACM.Resources.FixLcu.Part07</LogicalName></EmbeddedResource>
    <EmbeddedResource Include="Resources\Fix-LCU-Window.exe.b64.part08"><LogicalName>FACM.Resources.FixLcu.Part08</LogicalName></EmbeddedResource>
  </ItemGroup>
</Project>
